"""Export the club's REAL research track record to webapp/lib/track_record.json.

The web app's default view is a teaching tool; this file is the receipts. It is
generated by Python from the same engines that produced the verdicts (scan.py's
scan_universe + xsect.py + verdicts.jsonl), committed to the repo, and imported
statically by the frontend -- so the deployed app shows real research even when
the backend has no realdata/ (vendor CSVs are gitignored).

Run LOCALLY whenever the research record changes, then commit the JSON:
    python3 fetch_universe.py      # if data is stale
    python3 export_track_record.py
"""
import glob
import json
import os
from datetime import date

from data import load_csv
from scan import scan_universe, CANDIDATES, _verdict
from xsect import (load_panel, target_weights, run_panel, _first_active,
                   month_end_mask, momentum_12_1, robustness, sweep,
                   significance_vs_ew, panel_verdict,
                   EXCLUDE, TOP_N, ETF_COST)
from metrics import compute_metrics

import numpy as np
import pandas as pd

OUT = os.path.join('webapp', 'lib', 'track_record.json')


def wide_scan_summary():
    paths = sorted(glob.glob('realdata/*.csv'))
    benchmark = (load_csv('realdata/spy.csv', warn=False)['close']
                 if os.path.exists('realdata/spy.csv') else None)
    rows = scan_universe(paths, benchmark=benchmark)
    edges = sum(r['clean'] for r in rows)
    suspects = sum(r['survives_gate2'] and not r['clean'] for r in rows)
    rows.sort(key=lambda r: r['metrics']['total_return']
              if r['metrics']['total_return'] == r['metrics']['total_return'] else -1e9,
              reverse=True)
    top = [{
        'ticker': r['ticker'].upper(), 'strategy': r['strategy'],
        'oos_return': r['metrics']['total_return'], 'sharpe': r['metrics']['sharpe'],
        'trades_per_fold': r['trades_per_fold'], 'dsr': None if r['dsr'] != r['dsr'] else r['dsr'],
        'verdict': _verdict(r), 'red_flags': r['red_flags'],
    } for r in rows[:8]]
    return {
        'n_backtests': len(rows),
        'n_tickers': len({r['ticker'] for r in rows}),
        'strategies': list(CANDIDATES.keys()),
        'edges': edges, 'suspects': suspects,
        'dead': len(rows) - edges - suspects,
        'top': top,
    }


def thesis_001_summary():
    paths = sorted(glob.glob('realdata/*.csv'))
    stock_paths = [p for p in paths
                   if os.path.splitext(os.path.basename(p))[0] not in EXCLUDE]
    panel = load_panel(stock_paths)
    res = _first_active(run_panel(panel, target_weights(panel)))
    window = res.index

    scores = momentum_12_1(panel)
    rebal = month_end_mask(panel.index)
    ew = pd.DataFrame(np.nan, index=panel.index, columns=panel.columns)
    for t in panel.index[rebal]:
        row = scores.loc[t].dropna()
        if len(row) < TOP_N:
            continue
        wt = pd.Series(0.0, index=panel.columns)
        wt[row.index] = 1.0 / len(row)
        ew.loc[t] = wt
    ew_res = _first_active(run_panel(panel, ew.ffill().fillna(0.0))).reindex(window).dropna()

    spy_close_full = (load_csv('realdata/spy.csv', warn=False)['close']
                      if os.path.exists('realdata/spy.csv') else None)
    spy_m = None
    if spy_close_full is not None:
        from backtest import run_backtest
        spy = spy_close_full.reindex(window).dropna()
        _, spy_m = run_backtest(spy, pd.Series(1.0, index=spy.index), ETF_COST)

    # Baseline 3: random top-N picks each month, same machinery and seed as xsect.main --
    # panel_verdict needs it to answer "would any 10 names have worked?".
    rng = np.random.default_rng(1)
    rand_res = _first_active(run_panel(
        panel, target_weights(panel, picker=lambda row: rng.choice(
            row.index, size=TOP_N, replace=False)))).reindex(window).dropna()

    rob = robustness(res, spy_close_full)          # PSR + regime split + red flags
    sw = sweep(panel)                              # sensitivity neighborhood
    n_beat = sum(s['beats_ew'] for s in sw)

    m, m_ew = compute_metrics(res), compute_metrics(ew_res)
    m_rand = compute_metrics(rand_res)
    per_year = []
    for yr, g in res.groupby(res.index.year):
        ge = ew_res.reindex(g.index).dropna()
        per_year.append({
            'year': int(yr),
            'momentum': float((1 + g['net']).prod() - 1),
            'ew_universe': float((1 + ge['net']).prod() - 1) if len(ge) else None,
        })
    # The status is DERIVED, never asserted: the same xsect.panel_verdict the CLI and the
    # live Engine Room use, so the committed JSON cannot claim a verdict the engine rejects.
    sig = significance_vs_ew(res, ew_res, panel)
    pv = panel_verdict(m, m_ew, m_rand, spy_m, rob['flags'], sig)
    status = (f'{pv["status"]} ({n_beat}/{len(sw)} sensitivity neighbors beat EW) '
              '— pending Jonathan sign-off + paper trading')
    return {
        'spec': f'12-1 cross-sectional momentum, monthly, top {TOP_N} of '
                f'{panel.shape[1]} stocks, long-only, equal weight, n_trials=1',
        'window': [str(window[0].date()), str(window[-1].date())],
        'momentum': {'total_return': m['total_return'], 'cagr': m['cagr'],
                     'sharpe': m['sharpe'], 'max_dd': m['max_drawdown']},
        'ew_universe': {'total_return': m_ew['total_return'], 'cagr': m_ew['cagr'],
                        'sharpe': m_ew['sharpe'], 'max_dd': m_ew['max_drawdown']},
        'spy': None if spy_m is None else {
            'total_return': spy_m['total_return'], 'cagr': spy_m['cagr'],
            'sharpe': spy_m['sharpe'], 'max_dd': spy_m['max_drawdown']},
        'per_year': per_year,
        'probabilistic_sharpe': rob['psr'],
        'regime_split': rob['regimes'],
        'red_flags': rob['flags'],
        'sweep': sw,
        'sweep_beats_ew': f'{n_beat}/{len(sw)}',
        'status': status,
        'caveats': ['universe is survivorship-biased (today\'s liquid names)',
                    'single history, no parameter search (nothing to overfit, '
                    'but only one draw)',
                    'bull-market vehicle: loses in choppy/sideways regimes'],
    }


def verdict_log_summary():
    if not os.path.exists('verdicts.jsonl'):
        return {'n_real': 0, 'n_synthetic': 0}
    real = synth = 0
    with open('verdicts.jsonl') as f:
        for line in f:
            if not line.strip():
                continue
            v = json.loads(line)
            synth += bool(v.get('synthetic'))
            real += not v.get('synthetic')
    return {'n_real': real, 'n_synthetic': synth}


def main():
    record = {
        'generated': str(date.today()),
        'wide_scan': wide_scan_summary(),
        'thesis_001': thesis_001_summary(),
        'verdict_log': verdict_log_summary(),
    }
    def _np(o):
        if isinstance(o, (np.integer,)):
            return int(o)
        if isinstance(o, (np.floating,)):
            return None if np.isnan(o) else float(o)
        raise TypeError(f'not JSON serializable: {type(o)}')
    with open(OUT, 'w') as f:
        json.dump(record, f, indent=1, default=_np)
    print(f"wrote {OUT}")
    ws = record['wide_scan']
    print(f"  wide scan: {ws['n_backtests']} backtests / {ws['n_tickers']} tickers -> "
          f"{ws['edges']} EDGE?, {ws['suspects']} suspect, {ws['dead']} dead")
    print(f"  thesis 001: {record['thesis_001']['status']}")


if __name__ == '__main__':
    main()
